balena-os/balena-yocto-scripts

- automation/jenkins_build.sh
Reviewers: @floion @telphan @Page-
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-yocto-scripts/1)
> jenkins_build.sh: Fetch meta-resin before checkout to not have old refs

- build/barys
- build/build-device-type-json.sh
We need to display error messages when these commands are not available
and instruct the user to install them.
fixes #2 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-yocto-scripts/3)
> Check for existence of npm, node and jq

- build/build-device-type-json.sh
What I did:
- optional param to build in the given directory
- hide npm install stdout
- _reuse_ coffee-script installed inside of the `resin-device-types` - faster and safer and should fix the issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-yocto-scripts/9)
> faster builds and also fixes #8

- automation/jenkins_build.sh
> jenkins_build.sh: No more debug images in non-production builds

- automation/jenkins_build.sh
Run scripts located in the device repositories at tests/start.sh - This will allow us to have device specific tests.
Connects to #23
> jenkins_build.sh: Add ability to run a custom script 

- build/build-device-type-json.sh
Some package managers install nodejs as 'node', while others as
'nodejs'.
Also change the wording in the error message a little.
Signed-off-by: Michal Mazurek <michal@resin.io>
> build-device-type-json.sh: make this work on ubuntu

- build/build-device-type-json.sh
on some systems "which" prints to stderr if command is not found.
Signed-off-by: Michal Mazurek <michal@resin.io>
> build-device-type-json.sh: discard stderr when running "which"

- automation/jenkins_build.sh
We need this archive exposed as a Jenkins build artifact
> jenkins_build.sh: Deploy kernel_modules_headers.tar.bz2

- .gitignore
- automation/Dockerfile_yocto-build-env
- build/build-device-type-json.sh
- build/package.json
That removes it as a submodule dependency and allows
automatically fetching the updated versions according to semver.
Signed-off-by: Eugene Mirotin <eugene@resin.io>
> use npm deps

- automation/jenkins_build.sh
Connects to resin-os/meta-resin#320
> jenkins_build.sh: kernel_modules_headers is now filtered through gzip

- automation/Dockerfile_yocto-build-env
This dependency is needed for newer builds based on poky which
has a dependency on python3.
> Add python3 to automation/Dockerfile_yocto-build-env

- automation/Dockerfile_yocto-build-env
to use with poky morty.
This fixes the following poky morty error:
Please use a locale setting which supports utf-8.
Python can't change the filesystem locale after loading so we need a utf-8 when python starts or things won't work.
> Set the locale to UTF-8 for being able

- automation/jenkins_build.sh
The docker registry tags need to satisfy the following regex:
[\w][\w.-]{0,127}.
https://github.com/docker/docker/blob/master/vendor/github.com/docker/distribution/reference/regexp.go#L37
Make sure this is valid for our resinOS tags too.
> jenkins_build.sh: Make sure the docker registry tags are valid

- automation/jenkins_build.sh
Remove explicit use of origin namespace when checking out
meta-resin. If we want to specify a revision using a SHA1
this won't work so just simply git checkout $metaResinBranch.
> automation/jenkins_build.sh: Simplify git checkout

- automation/jenkins_build.sh
When we checkout a meta-resin revision for building we must also take into
consideration that such a revision might be from an external contributor's
fork sent as a pull request.
> automation/jenkins_build.sh: Allow checkout of forked pull requests

- build/barys
Currently barys will append local variables to conf/local.conf each time
it's run, leading to a long repeated list after a couple of runs.
Clean it up before appending.
Signed-off-by: Michal Mazurek <michal@resin.io>
> barys: reset, don't append, additional variables

- automation/jenkins_build.sh
When we checkout a meta-resin revision for building we must also take into
consideration that such a revision might be from an external contributor's
fork sent as a pull request.
> automation/jenkins_build.sh: Allow checkout of forked pull requests on the 1.X branch

- automation/jenkins_build.sh
Fixes https://github.com/resin-os/resinos/issues/310
> jenkins_build.sh: Use prod as version suffix for production images

- automation/jenkins_build.sh
for an archived build, not the whole directory
The image maker expects the contents of the build dir artifacts to be in
$_deploy_dir/image/, not the entire directory with subdirectories.
> jenkins_build.sh: Copy just the contents of a directory

- build/generate-conf-notes.sh
Fix commands output for longer machine description.
Replace ASCI art with ResinOS.
> generate-conf-notes.sh: Minor tweaks

- automation/jenkins_build.sh
> jenkins_build.sh: Copy to path expected by the resin image maker

- automation/jenkins_build.sh
Based on the threads listed below, this should resolve the issue, which
is related to building an image with the interactive terminal flag (-t)
but then running it without the flag.
https://github.com/moby/moby/pull/4882
https://github.com/moby/moby/issues/4857
https://github.com/moby/moby/issues/5327
Change-Type: patch
> Attempt to fix unrecognized input header error

- automation/jenkins_build.sh
We remove the "-i" arg as that throws the following error:
"cannot enable tty mode on non tty input"
We also add the "--rm" flag to automatically remove the container when it exits
as it makes no sense for it to be running after exiting.
> jenkins_build.sh: Fix issues with "docker run" of resin/resin-img

- automation/jenkins_build.sh
Currently we call this script from Jenkins 4 times in a row: for managed production build,
for managed development build, for unmanaged production build and for unmanaged development
build. For various reasons related to the Jenkins environment and not only, one of these builds
can fail. If the second, third or fourth of these builds fail, when retriggering the upstream
Jenkins job to redo the deployment it will error out on the code highlighted here complaining that
deployment is done. That should not be an error and it should only throw a warning and continue with
the rest of the downstream build jobs to finish deploying successfully all the resin build flavours
> jenkins_build.sh: Do not error out when deployment has been already done

- automation/jenkins_build.sh
There may be cases where deployment is not fully done (network
errors for example). In such cases, we force the redeployment.
> jenkins_build.sh: Handle partial deploys

- automation/Dockerfile_yocto-build-env
We need npm when building the yocto image for the .json generation troutine.
> Dockerfile_yocto-build-env: Add npm to yocto-build-env image

- automation/Dockerfile_yocto-build-env
Yocto Morty can build a libsdl-native so there is no need for it in the docker image.
Also we install python 2.7 as it is explicitly needed by some packages. E.g. xcb-proto-native
> Dockerfile_yocto-build-env: Do not include SDL

- build/barys
Allow enabling the Yocto build history feature from barys.
> build/barys: Add --build-history flag

- automation/jenkins_build.sh
jenkins_build.sh should also be able to run outside of the jenkins environment
and run the yocto build in a docker container.
> jenkins_build.sh: Allow non-jenkins docker container builds

- automation/Dockerfile_yocto-build-env
The Yocto Pyro build process is more strict about which packages
it requires, add packages for: ip, ping, scp, ssh
> Dockerfile_yocto-build-env: Add some packages for Pyro

- automation/jenkins_yocto-build-env.sh
Get the current short commit ID by calling git rather than
relying on Jenkins to inject the variable.
> automation/jenkins_yocto-build-env.sh: Get revision directly

- automation/Dockerfile_yocto-build-env
- automation/jenkins_yocto-build-env.sh
Package ping is a virtual package so we use the actual providfer called iputils-ping
> Dockerfile_yocto-build-env: Use correct ubuntu package name for ping

- automation/jenkins_build.sh
Do a docker pull on the resin/yocto-build-env image before
starting the build. This means we always get the latest version
of the image.
> automation/jenkins_build.sh: Pull yocto-build-env

- build/barys
I've stumbled on a fact that barys can't accept empty values to `-a`, i.e. `barys -a FOO=`. If I do `barys -a FOO=""` it makes an extra pair of quotation marks thus still not an empty value. Here is a quick fix of the condition so that it allows a `FOO=` form. The rest of the code should play nice and insert an empty string between the quotes.
Please review. Seems to work fine in my setup.
> Empty values to -a

- build/build-device-type-json.sh
Currently if npm fails it is difficult to debug.
> build-device-type-json.sh: Make npm failures louder

- build/package.json
This fixes a warning during builds and also makes the code license
clearer.
> build/package.json: Set a valid license

- build/barys
We can already set the `--development-image` flag for barys to build a development image
> Allow to build a custom "production" resinos image

- build/barys
There can be cases where there is no fstype. For example this is true when we
build generic image for resinOS in container. This patch makes barys only warn
if there is no fstype/image defined.
> barys: Don't error out if there is no fstype defined.

- build/barys
This is useful for example to add variables suffixed with machine name, for example:
TARGET_REPOSITORY_genericx86-64=my.docker.repo/custom/targetimage
> Allow additionnal variables that contains "-" char

- automation/jenkins_build.sh
When that is the case, the UI doesn't offer raw images for download.
> jenkins_build.sh: UI uses `docker-image` as deploy artefact

- automation/prepare-and-start.sh
In some cases Yocto wants to initialize git repos, but it will fail because
git credentials are missing.
This commit sets dummy git credentials for user "builder" before starting a build.
Signed-off-by: Sebastian Panceac <sebastian@resin.io>
> Set dummy git credentials for "builder" user

- automation/Dockerfile_yocto-build-env
Various BSPs may need additional host tools available.
for instance, we are adding now dos2unix because it is needed by
https://github.com/varigit/meta-variscite-fslc/blob/rocko/recipes-connectivity/wlconf/wlconf.bb#L35
> Dockerfile_yocto-build-env: Add dos2unix to container

- build/barys
Currently if barys is run with -d, DEVELOPMENT_IMAGE is
set to 1 in local.conf. If barys is run next time without
-d, DEVELOPMENT_IMAGE is not set back to 0. Hence the
generated image is still a dev image with serial enabled
etc.
Change-type: Patch
Changelog-entry: Fix for barys with -d and without -d
Signed-off-by: Zubair Lutfullah Kakakhel <zubair@resin.io>
> barys: pass DEVELOPMENT_IMAGE = 0 when -d is not passed

- automation/jenkins_build.sh
- build/barys
- build/barys.changelog
Starting with resinOS 2.14.0 the managed and managed builds are now
unified. Remove the configuration for such build flavors.
> Unify managed/unmanaged builds

- automation/jenkins_build.sh
We now have unified builds for managed and unmanaged. So the decision was that for
each build, we deploy to both S3 buckets for resinio and resinos at the same time.
> jenkins_build.sh: Deploy to both resinio and resinos S3 buckets

- automation/jenkins_build.sh
Signed-off-by: Alexis Svinartchouk <alexis@balena.io>
> jenkins_build.sh: Use ts-node instead of coffeescript for img prepare

- automation/jenkins_build.sh
Change-type: major
This goes with https://github.com/balena-io/resin-image-maker/pull/216
I'm not sure who uses resin-flasher.img so I didn't changed it.
> Rename images from resin.img to balena.img

- automation/jenkins_build.sh
The in-container bash code can also error so we need to make sure
we propagate this error outside the container so Jenkins fails and
marks the build job accordingly.
> jenkins_build.sh: Add error check for the in-container bash code

- automation/Dockerfile_yocto-build-env
balena-cli will be used to push the built images as releases to a balena
application
> Add balena-cli to yocto-build-env docker image

- automation/jenkins_build.sh
We have customers that do not want to have the kernel modules headers generated.
So let's make sure the deploy won't fail when these headers are not present.
Changelog-entry: Do not error if the kernel headers are not generated
> jenkins_build.sh: Do not error if the kernel headers are not generated

- automation/jenkins_build.sh
This is needed so that the UI can pick it up.
Changelog-entry: Deploy the device type logo so the UI can pick it up
> jenkins_build.sh: Deploy the device type logo

- automation/jenkins_build.sh
The resin-img docker image has changed to open-balena-base 8.0.0
which in turn is based on debian:buster. This version of debian
does not include the s3cmd package in it's repositories anymore.
Instead it provides a replacement package called s4cmd
(https://packages.debian.org/buster/s4cmd) which "is intended as
an alternative to the existing s3cmd tool, enhancing performance
and support for large files, and coming with a number of additional
features and fixes".
> jenkins_build.sh: Switch s3cmd with s4cmd

- automation/jenkins_build.sh
Since we switched from s3cmd to s4cmd we also need to use the
del command because s4cmd lacks the rm command.
> jenkins_build.sh: Use s4cmd del command instead of rm

- automation/jenkins_build.sh
Since s4cmd does not have the "--acl-public" option we use the new
--API-ACL option that allows us to set canend ACLs for the objects
we upload to S3. We use the "public-read" canned ACL that does:
"Owner gets FULL_CONTROL. The AllUsers group gets READ access."
Also we remove the "--skip-existing" option which is not present
in s4cmd.
> jenkins_build.sh: Use canned ACL and remove obsolete option

- automation/jenkins_build.sh
We need to use -f (force overwrite) otherwise s4cmd fails:
[Thread Failure] File already exists: <s3_bucket>/latest
> jenkins_build.sh: Use put command with -f for latest file

- automation/jenkins_build.sh
The sync command is deprecated in s4cmd in favour of dsync. And also
the existing deprecated sync command in s4cmd does the sync in a
different manner from the s3cmd sync command in the sense that it
makes a copy of the local dir in the remote dir and in our case we
end up with duplicate dirs in the target path.
> jenkins_build.sh: Use dsync instead of deprecated sync command

- .gitignore
Since this file seems to be generated by the barys script and it's not
supposed to be checked in, let's ignore it.
Signed-off-by: Sven Schwermer <sven.schwermer@disruptive-technologies.com>
> git: Ignore package-lock.json

- build/barys
Setting `--supervisor-tag` to enable building for a specific supervisor tag sets the `SUPERVISOR_TAG` value. That is the correct variable to set according to meta-balena (see at https://github.com/balena-os/meta-balena/blob/8d5057b45e1965e6c27c03a95d2211ae47842331/meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc#L20 ) but in the device types' `local.conf.sample` the `TARGET_TAG` variable was set, see for example https://github.com/balena-os/balena-raspberrypi/blob/078b0add0345e94f27c15d98256f8c7b61b66761/layers/meta-balena-raspberrypi/conf/samples/local.conf.sample#L45-L46 and thus barys' setting was not applied.
Looking at the available recipes, the `SUPERVISOR_TAG` should be set and in the device types' `local.conf.example` files should be updated to refer to …
> barys: correctly apply SUPERVISOR_TAG variable in local.conf

- automation/jenkins_build.sh
This is needed so that browsers can load the logo.
Since s4cmd doesn't have a `modify` command, I
had to `put` the logo again.
Connects-to: #166
HQ: https://github.com/balena-io/balena/issues/1818
See: https://github.com/bloomreach/s4cmd#--api-contenttypestring
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>
> jenkins_build.sh: Set a content-type to the device type's logo.svg

- automation/jenkins_build.sh
This is useful for passing SD8887_FROM_SOURCE for example so that
the Fin build will compile the wifi and bt driver from source.
> jenkins_build.sh: Allow for passing additional arguments to barys

- build/build-device-type-json.sh
When building a device type JSON manifest, any syntax error is handled
by printing a message about node being unavailable, even when it's
installed and working.
Check that node is installed and executable before building the
manifest, and exit early with the existing message if not. Otherwise,
print stderr to the console for debugging.
> build-device-type-json: show stderr on failure

- automation/jenkins_build.sh
If leviathan test suites are found in the checkout of
meta-balena we should package them up with the jenkins artifacts.
Connects-to: https://github.com/balena-os/meta-balena/pull/2113
> jenkins: deploy test suite from meta-balena

- automation/jenkins_build.sh
The jenkins leviathan builds will attempt to flatten these artifacts on extract (`unzip -j`) so make sure the test suites are a separate tarball inside the artifacts.
> jenkins: compress test suites inside jenkins artifacts

- automation/balena-lib.sh
- automation/jenkins_build.sh
Instead of using the master tag for helper containers, use those with a tag that matches the repository revision building them if required.
This allows to make changes to the helper containers without affecting the build of previous releases.
> Dynamically build helper containers

- automation/Dockerfile_balena-push-env
- automation/Dockerfile_yocto-build-env
- automation/balena-lib.sh
- automation/jenkins_build-containers.sh
- automation/jenkins_build.sh
This set of commits move the helper containers used to build and push releases to be source controlled instead of using the `latest` version.
This means that from this version onwards we will be able to modify helper scripts and they will only affect releases that use the balena-yocto-script revision that contains the changes.
Note that older revisions that use master will still break is `master` is updated to something that is not working. Those older revisions should be updated to this revision.
> Use version controlled helper containers

- automation/Dockerfile_yocto-build-env
Otherwise bitbake fails with the following error:
Your Python 3 is not a full install. Please install the module
distutils.sysconfig (see the Getting Started guide for further
information).
> Dockerfile_yocto-build-env: Install required python3-distutils module

- automation/jenkins_build.sh
- build/barys
As part of a full rename away from legacy resin namespaces the
following device compatibility changes are required to align
with meta-balena changes.
- packaging scripts
Changelog-entry: Rename resin image types to balena
Depends-on: balena-os/meta-balena#2118
> balena-yocto-scripts: rename resin image types to balena

- build/barys
The current method does not support multiple layers named with names
following `meta-balena-*` so this change will search for the required
`bblayers.conf.sample` file before assigning the template layer.
Changelog-entry: Improve template layer matching
> Improve template layer matching

- automation/Dockerfile_balena-push-env
- automation/Dockerfile_yocto-build-env
- automation/entry_scripts/prepare-and-start.sh
- automation/include/balena-docker.inc
- build/balena-build.sh
This is complementary to the following meta-balena PR:
https://github.com/balena-os/meta-balena/pull/2167/commits
In summary:
- Shortens the installation path in the build containers so that balena-engine socket fits
- Adds hosttools dependencies to build containers
> Replace docker with balena-engine in BalenaOS build

- automation/include/balena-api.inc
When creating a public app, set the access rights so that OS developers can see the app in their accounts.
> Allow access to OS developers to public apps

- automation/jenkins_build.sh
- build/barys
* Barys and `jenkins_build.sh` argument `--supervisor-tag` becomes `--supervisor-release` in preparation for the OS to use `release_version` to fetch the supervisor image
* Build jobs needs to change the configuration variable `supervisorTag` with `supervisorRelease`
* Build jobs needs to change `metaResinBranch` to `metaBalenaBranch`
> Rebrand resin to balena and use release_version to specify supervisor

- README.md
- automation/Dockerfile_yocto-block-build-env
- automation/entry_scripts/balena-build-block.sh
- automation/include/balena-deploy.inc
- automation/jenkins_build-blocks.sh
* Adds a `jenkins_build-blocks.sh` script to build and deploy package based hostos blocks. These blocks are defined in a contract.
* Extend `balena-deploy` to deploy OS block and hostOS apps.. A hostOS is deployed from a compose file that is automatically generated from the blocks that define the hostOS.
* Update the README to mention the main scripts in the repository.
> Add hostos blocks support

- .versionbot/CHANGELOG.yml
This file allows other components to uniquely parse the information that
is contained in the changelog. It will be automatically managed by
versionist by appending the new commits on top. This is needed to
provide nested-changelogs.
Changelog-entry: Add a parsable representation of the changelog
> versionbot: Add changelog yml file

- automation/entry_scripts/balena-deploy-block.sh
Fix the legacy way of tagging releases with a string variant and the OS
version as this is still being used by the UI.
> balena-deploy-block: Do not add variant suffix to release tag

- automation/include/balena-deploy.inc
When creating a public app, the workdir is used to retrieve the URL
used in the public app creation.
> balena-deploy: Provide working directory when deploying hostapp

- automation/include/balena-lib.inc
Avoid returning an empty path when we are running in containers
where /work does not exist.
> balena-lib: Fix device dir when running in Jenkins containers

- automation/Dockerfile_balena-push-env
- automation/Dockerfile_yocto-build-env
This is necessary for AMI preloading to work, additionally it has been more than a year since the last update, we should keep up.
> Update balena-cli to 12.50.1 in automation dockerfiles

- automation/include/balena-deploy.inc
These changes are currently made in the Jenkins job, so it's preferrable
to have it done by the packaging scripts.
> balena-deploy: Set leviathan networkWireless mode based on device slug

- automation/conversion_scripts/revert-overrides.py
> revert_overrides: Add intel-quark to architecture overrides

- automation/entry_scripts/prepare-and-start.sh
- automation/include/balena-api.inc
- build/balena-build.sh
The balena-build.sh script accepts a token in the command line. This
commit modifies the prepare-and-start.sh script to use it if
available.
> prepare-and-start: Do not ignore token when passed in command line

- automation/include/balena-deploy.inc
As per https://jel.ly.fish/a533a6bd-1c98-412c-ae60-8427e3f7b005,
the /device-types/v1 endpoint is deprecated and we can remove
the logo from the device repos so we can also stop handling it
from here. Instead, the logo will be used from the hw contracts.
> balena-deploy.inc: Do no deploy device logo to deprecated endpoint

- automation/jenkins_build.sh
If meta-balena has submodule updates we want to make sure to use them.
See: https://github.com/balena-os/meta-balena/pull/2514
> jenkins_build: Use recurse-submodules when checking out meta-balena

- automation/include/balena-deploy.inc
This will allow us to make changes to config.js in meta-balena without
breaking the deploy steps. If additional changes are needed at runtime
the substitutions can be made by the leviathan Jenkins job.
See: https://github.com/balena-os/meta-balena/pull/2514
> balena-deploy: Avoid patching test suites config.js during deploy

- automation/entry_scripts/balena-generate-ami.sh
- automation/jenkins_generate_ami.sh
Surface the preloaded app commit as a variable that can be overridden in
the build job. Default to "current" to maintain existing behavior when
the variable isn't set.
> jenkins_generate_ami: surface preload app commit as variable

- automation/entry_scripts/balena-generate-ami.sh
Remove BALENA_PRELOAD_COMMIT from required env vars, as we have a
default if it's not specified.
> automation: ami: make BALENA_PRELOAD_COMMIT optional

- automation/include/balena-deploy.inc
jq returns null by default when a given key isn't found, ensure that
when getting the value of deployRawArtifact, we get an empty variable
instead, which is checked later on to determine if that file should be
deployed
> deploy: ensure deployRawArtifact is empty instead of null

- automation/include/balena-lib.inc
Git 2.35.2 was released to fix a security issue with multi-user
machines. Add `device_dir` to the whitelist to avoid this error.
> balena-lib: fix 'fatal: unsafe repository'

- automation/include/balena-lib.inc
Commit 445d6d1fcfce97f85ffcfedc0083eb658a734321 does not fix
the issue because it is missing the --global arg without which
the git config command fails.
> balena-lib: fix 445d6d1fcfce97f85ffcfedc0083eb658a734321

- .gitignore
- automation/entry_scripts/balena-deploy-block.sh
- automation/include/balena-deploy.inc
- automation/include/balena-lib.inc
- build/contracts/blueprints/os-contracts.yaml
- build/contracts/generate-oscontracts.js
- build/contracts/package-lock.json
- build/contracts/package.json
This PR corresponds to improvement https://jel.ly.fish/improvement-balenaos-contracts-3a7f1e9 (internal)
* It requires all device type repositories to add the https://github.com/balena-io/contracts submodule.
* It requires all private device types build jobs to configure the github credentials in the jobs binding so the private contract repo can be cloned
[Bindings](https://drive.google.com/file/d/1mqXrUW6yc7ASkeENcHZQ7EizcbW3PDP1/view?usp=sharing) (internal)
* It requires to modify device types jobs to include a `final` argument
* It requires to modify the `yocto-deploy-board` and `balenaOS-deploy` jobs to pass the `final` argument.
The jenkins jobs changes above have been implemented in the `yocto-board-template` job, so all device types need to move and inherit from this template. …
> Generate balena OS contracts

- automation/include/balena-lib.inc
Otherwise patch updates of ESR branches move the ESR phase when they
should not. For example, if 2022.1.1 is current, 2022.1.2 is also
current and should not move 2022.1.1 to sunset.
> balena-lib: Tag ESR fleets with patch independent tags

- automation/include/balena-lib.inc
When we patch an ESR branch, for example from v2022.1.0 to v2022.1.1,
do not update the next, current, sunset ESR  phases as they remain the
same.
> balena-lib: release_finalize: Do not retag phase for ESR branch patch

- automation/include/balena-deploy.inc
As part of rebranding, resin docker repos were renamed to balena, and
resin/resin-img no longer receives updates. Change the image we pull to
process OS images from resin/resin-img to balena/balena-img.
> balena-deploy: s/resin-img/balena-img

- automation/include/balena-api.inc
Applications can be fleet, blocks or apps, and hostapps need to be set
as apps.
> balena-api: On hostapp creation, set class to app

- build/barys
Recent versions of meta-balena include a balena-rust layer used to
specify a distro-set Rust version across all supported Yocto versions
As such, the syntax of this layer also needs to be converted.
Relates-to: https://github.com/balena-os/meta-balena/pull/2750
> barys: Add balena-rust to syntax conversion step

- automation/jenkins_build.sh
> jenkins_build: Only deploy AMI after deploying a final release

- automation/jenkins_generate_ami.sh
The AMI preload application no longer lives in the balena_os organization so allow to provide a different token.
> jenkins_generate_ami: use a different token

- automation/entry_scripts/balena-generate-ami.sh
- automation/jenkins_build.sh
- automation/jenkins_generate_ami.sh
Building OS development images is useful for example when debugging and testing AMI images.
> jenkins_build: secure boot & FDE AMI images support

- automation/entry_scripts/balena-generate-ami.sh
On aarch64 this fails with `Invalid machineArchitecture value 'arm64' for tpmSupport`
> balena-generate-ami: Enable TPM support on x86_64 only

- automation/entry_scripts/balena-generate-ami.sh
No need to provide a key name as the instance only needs to be accessible via balenaCloud.
> balene-generate-ami: remove key name

- automation/include/balena-api.inc
The balenaAPI has replied both `OK` and `"OK"` to patch requests. Accept any of them as long as they contain OK.
> balena-api: ignore quotes from API replies

- build/barys
When parsing additional variables to be passed to the bitbake build, keys and values are split using equals as a delimiter. However, the splitting process does not split only on the first occurrence, which results in removing equals signs from the value as well. This is problematic with base64 encoded strings, which are padded with equals signs.
Split only on the first occurrence, leaving the value intact.
> barys: fix removal of equals sign from argval

- automation/entry_scripts/balena-deploy-block.sh
- automation/include/balena-deploy.inc
- automation/jenkins_build.sh
When building signed images, add the secureBoot feature flag into the OS contract. This is needed for other components to identify secureBoot compatible software releases.
> balena-deploy: add secureBoot feature into contract

- automation/include/balena-deploy.inc
This artifact did not contain kernel sources since Yocto Thud.
Changelog-entry: The kernel_source tarball is no longer created by meta-balena
> balena-deploy: Newer meta-balena do not create a kernel_source tarball

- automation/include/balena-api.inc
- automation/include/balena-deploy.inc
There is a bug when the curl GET to check if a DT is private or not fails - it assumes the device type is private. This can lead to s3 artifacts for public DT's not being marked as public-read, if the curl fails (for example if there are api errors or connectivity issues)
> Fail deploy if script fails to find DT

- automation/Dockerfile_yocto-build-env
To enable us to use `bitbake -c devshell foo` in container
> Dockerfile_yocto-build-env: Add screen

- automation/Dockerfile_yocto-build-env
These are required for the UCM-iMX9 build
> Dockerfile_yocto-build-env: Install rsync and uudecode host dependencies

- automation/include/balena-deploy.inc
This seems to cause docker images --format to fail
> balena-deploy: Remove docker.io when pulling image

- automation/include/balena-deploy.inc
- automation/include/balena-lib.inc
This is needed by the balena-push-env helper image that needs the balena-yocto-scripts version but has no way of getting that info otherwise.
> automation/include: Pass helper image version

- build/balena-build.sh
Yocto already splits the build sstate by target arch, native arch, toolchains, and machine where applicable.
Keeping the caches separated by device type prevents sharing of common cache steps between identical toolchains and architectures.
> balena-build: avoid using device-type as a prefix in yocto sstate

- .github/workflows/flowzone.yml
- automation/Dockerfile_yocto-build-env
- automation/jenkins_generate_ami.sh
- docker-bake.hcl
This allows us to build and publish fewer helper images.
> Merge AMI publishing dependencies into yocto-build-env

- build/balena-build.sh
This reverts commit f4a9566941083770151ebe3edd78e9866b4856fb.
The original change introduced unexpected breaking issues in the build cache as captured in [this](https://balena.zulipchat.com/#narrow/stream/345889-balena-io.2Fos/topic/.E2.9C.94.20Build.20Failures.20-.20bigmak-imx8m-plus) thread.
> Revert "balena-build: avoid using device-type as a prefix in yocto sstate"

- automation/include/balena-lib.inc
Git describe does not include commit tags by default, and only annotated tags are shown.
This behaviour was fine until a recent CI issue changed the types of tags used to version the repositories.
This commit allows supporting of both types while the CI issue is investigated.
> Support commit tags when extracting version tag from git

- automation/include/balena-lib.inc
When a ESR release is deployed a tag with the base meta-balena version is created. This is used by the API to check for a valid OS version for updates.
The current mechanism to find the base version only provides an ESR version for the first commit after the branch has been created.
Using merge-base to find the common ancestor and `tag --points-at` to find the actual tag works for all commits after the branch is created.
> balena-lib: improve base tag detection

- automation/include/balena-deploy.inc
This is where the RPI family deploys provisioning artifacts.
> balena-deploy: deploy usbboot if available

- .github/workflows/generic-amd64.yml
- .github/workflows/yocto-build-deploy.yml
This is a helper job to avoid having to mark all build/test matrices as required, as this job will always run and return success or failure.
> Add catchall job to yocto-build-deploy for merge requirements

- .github/workflows/generic-amd64.yml
We do not need to run the workflow on close/merge, and we can skip the manual workflow runs on this project as each device type will have it's own workflow in the device repos supporting manual triggers.
> Update the triggers on the example test workflow

- automation/Dockerfile_balena-push-env
- automation/Dockerfile_yocto-build-env
Upgrade the image base from Ubuntu:18.04 to Ubuntu:22.04, bringing a new docker engine version, and compatibility with cgroup v2 on the host.
> Base image upgrade

- .github/workflows/generic-amd64.yml
- .github/workflows/yocto-build-deploy.yml
Default to self-hosted X64 with KVM for now to align with Jenkins but in the future
we should consider using GitHub hosted runners for the testbot workers.
> Support runner selection in the test matrix

- .github/workflows/yocto-build-deploy.yml
I spotted a typo/bug in the check for secure boot this while [checking this test run](https://github.com/balena-io-experimental/balena-raspberrypi-gha/actions/runs/9681366732/job/26756255483#step:29:27):
```
if [ -n "${{ inputs.sign-image }}" = "true" ]; then
```
Then I noticed we could use `inputs.sign-image` directly, without going through a new variable `SECURE_BOOT_FEATURE_FLAG`. This also removes the small complexity of one thing being true/false and the other being yes/no.
> GHA workflow: Simplify check for secure boot

- .github/workflows/yocto-build-deploy.yml
We had typos in two cases, in which we missed the opening quote.
This seems to be final blocker preventing a complete execution of the workflow!
> Fix quoting of $GITHUB_OUTPUT

- .github/workflows/yocto-build-deploy.yml
Uploading artifacts to GH artifact storage when PR is merged (closed event) is wasterful. Since they are only uploaded for temporary basis so it can be used for testing. Hence, the PR to stop doing that for `closed` PR event
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
> Stop uploading to GH artifacts storage when PR is closed

- .github/workflows/yocto-build-deploy.yml
As there are currently more device types without tests than with, and some of those with tests need to provide overrides anyway, it's simpler to assume an empty test matrix unless provided.
> Do not run any tests by default unless provided by calling workflow

- .github/workflows/yocto-build-deploy.yml
We are publishing hostapp releases to staging already, we should start including the associated S3 files as well.
> Remove dry-run flag from S3 upload

- .github/workflows/yocto-build-deploy.yml
Since we have moved to workflows for tests instead of status checks, we have to fetch the workflow runs for the appropriate commit to determine a test pass/fail.
notable points for review:
1. as we're using workflow names to find the appropriate run, worflow name in the device repo must be named after machine name - updated the example here to reflect that
2. If the test matrix is empty, don't run the `check-merge-tests` step - and therefore do not finalise the hostapp. Is this a valid way of doing that. This is to stop device's releases being finalized without undergoing tests
> use workflow runs of PR to get test results

- .github/workflows/yocto-build-deploy.yml
Currently the workflow breaks if no test matrix is provided. This PR was tested both with and without a test matrix.
> Fix handling of empty test matrix input

- .github/workflows/generic-amd64.yml
- .github/workflows/yocto-build-deploy.yml
These currently differ between environments, and we will need to start supporting environment names that are not the same as the balena host.
> Use env vars BALENA_HOST and BALENACLOUD_SSH_URL when provided

- .github/workflows/yocto-build-deploy.yml
when building + deploying or a private DT , the check to see if the DT is private fails. This is due to https://github.com/balena-os/balena-yocto-scripts/blob/master/automation/include/balena-api.inc#L424 using this function: https://github.com/balena-os/balena-yocto-scripts/blob/master/automation/include/balena-lib.inc#L191 - which uses the jenkins deployTo variable to select the correct api url and token.
> Fix os contract building for private device types

- .github/workflows/yocto-build-deploy.yml
This is meant to keep the defaults of `deploy-s3` and `deploy-hostapp` consistent.
> By default, deploy hostapp on push only

- .github/workflows/yocto-build-deploy.yml
The "All jobs" job is used for branch protection
as it captures the overall success/fail of all
the test matrices and build.
However without a unique name we are unable
to identify the device type in order to mark it as required.
This change adds a single instance matrix
to the build job and as a result will append the machine name and deploy environment in the job name.
Depends-on: https://github.com/balena-os/.github/pull/69
> Add unique unique identifiers to summary job

- .github/workflows/yocto-build-deploy.yml
The logic for this step was broken - even when no test matrix was provided, it was chekcing for test results, which we don't want (as they won't exist)
> Fix if condition for checking merge commit test results

- .github/workflows/yocto-build-deploy.yml
using pip to install python packages also installable by debian is not recommended, and leads to errors while trying to do so. Switch to using apt-get to install s4cmd to address this
> use apt-get to install s4cmd instead of pip

- .github/workflows/yocto-build-deploy.yml
We currently have many `8cpu` runners available that are migrating from Jenkins that we should allow to use for yocto builds.
As long as some runners don't have the `yocto` tag so we don't bottleneck the runner queue for other orgs.
> Restrict runners via yocto label, not 16cpu

- .github/workflows/yocto-build-deploy.yml
This prevents uploads of artifacts that will never be used - as they are only used in the tests step, if there are no tests then no need to upload
> only upload artifacts when test_matrix is defined

- .github/workflows/yocto-build-deploy.yml
The previous API command was limited to 20 results, and did not correctly evaluate to false when no workflow runs were found.
> Improve checking of previous test results

- .github/workflows/genericx86-64-ext.yml
Using genericx86-64-ext as its smaller, faster to build and the repo is blocked less often.
In this particular case the `balena-generic` repo is blocked due to an upstream change breaking the HUP suite on secure boot devices. This is a problem as we need to merge other meta-balena fixes to fix builds for `balena-generic` - using `balena-intel` , already working with GHA workflows unblocks fixes to this workflow.
We don't actually care about the device type being testedl, just that the workflow is tested
> use genericx86-64-ext image for testing the workflow

- .github/workflows/yocto-build-deploy.yml
From actions/checkout README
> The auth token is persisted in the local git config. This enables your scripts to run authenticated git commands. The token is removed during post-job cleanup. Set persist-credentials: false to opt-out.
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
> patch: Stop persisting credentials in actions/checkout

- .github/workflows/yocto-build-deploy.yml
Applies symmetric encryption (PBKDF2 hardened) to balenaOS build assets prior to uploading them to GitHub for temporary storage between builds. Decrypts assets after downloading.
Requires: https://github.com/balena-os/.github/pull/83
Depends-on: https://github.com/balena-os/balena-generic/pull/525
https://balena.fibery.io/Work/Improvement/Encrypt-artifacts-used-between-jobs-2070
> Encrypt balenaOS artifacts at rest in GitHub

- .github/workflows/yocto-build-deploy.yml
This is required for cloning private submodules - as the default behaviour means the token is scoped only to the repository the workflow is running on
> use github app installation token for device repository cloning

- .github/workflows/yocto-build-deploy.yml
A previous commit added quotes to some of the `balena deploy` command args - when $status or $_debug aren't defined, this means empty quote gets passed as an arg, making the CLI fail.
> fix balena deploy quotes

- .github/workflows/yocto-build-deploy.yml
When evaluating expressions for cancel-in-progress, certain parameters may not be available at the time of evaluation.
For instance, the github.job context is not accessible, as it's specific to the running job and not the concurrency group.
> Fix concurrency and cancel in progress contexts

- .github/workflows/yocto-build-deploy.yml
Some device types (generic-armd64) need to run the test
suites twice for the same base image, once with secure boot
vars enabled in Leviathan, and once without.
Rather than run the suites in series, or require building the
image twice, we can allow the test matrix to define separate runs
for the two modes.
> Expose secure boot testing features via matrix input

- .github/workflows/yocto-build-deploy.yml
The existing method of using labels allows for
Actions Time Of Check to Time Of Use (TOCTOU) attacks because we do not associate the label with any commit.
This action requires approvals via reactions on a unique comment generated for each workflow run.
> add review-commit-action to wait for approvals on PRT events

- .github/workflows/yocto-build-deploy.yml
nitpicky fix, we don't use the CLI when not deploying - so no need to check its version
> remove CLI check if not deploying

- .github/workflows/yocto-build-deploy.yml
The modern awscli command is optimized for these
tasks and better maintained.
This enables some other work to use S3 as a download mirror.
See: https://github.com/balena-os/balena-yocto-scripts/pull/443
> Use official aws cli binaries and commands

- .github/workflows/yocto-build-deploy.yml
This is the more secure approach that defaults
to lowest possible permissions.
> Set explicit permissions at the job level

- .github/workflows/genericx86-64-ext.yml
- .github/workflows/yocto-build-deploy.yml
THis is to allow the workflow to function under an org with restricitve github token permissions
> Set additional github token permissions

- .github/workflows/yocto-build-deploy.yml
This change makes the legacy NFS cache mount
optional, and will not fail the build if unset
or unreachable.
Instead, if the NFS is available it will be used
as a read-only mirror for shared downloads,
but will not be updated with new files.
This allows the per-device sstate to be ephemeral
and best effort, with automatic size and expiry limits
enforced by GitHub and scoped to the repository and branch.
See: https://balena.fibery.io/Work/Project/Secure-solutions-for-GHA-yocto-shared-cache-692
Supersedes: https://github.com/balena-os/balena-yocto-scripts/pull/351
> Use S3 and GitHub Actions for yocto build cache

- .github/workflows/yocto-build-deploy.yml
Required by:
* https://github.com/balena-io/environment-production/pull/2458
This PR fixes the AMI build , test and deployment for the AMIs absed on `generic-amd64` .
It doesn't enable sharing these publicly, which will require further work.
Marked as draft as 2 changes pending before merge - as conditions have been set on various steps to execute on PRs, which they shouldn't when we're done
> re-enable AMI deploys

- .github/workflows/yocto-build-deploy.yml
Otherwise encrypted images are unable to be compressed. This saves a lot of space and time on uploading/downloading artifacts.
Compressing images before upload makes a big difference because a bunch of the image space is zeros. In testing I saw the compressed artifacts were only 26% the size of the uncompressed artifacts.
With encryption forced, the artifacts are ~1.2GB on this PR. Previously encrypted artifacts for generic-amd64 were ~4.6GB 🎉
> Compress artifacts with gzip and zstd before encrypting

- .github/workflows/yocto-build-deploy.yml
See: https://balena.fibery.io/Work/Improvement/Update-yocto-workflow-to-use-S3-as-download-mirror-2466
> Use dedicated AWS S3 buckets for download mirrors

- .github/workflows/yocto-build-deploy.yml
This allows the build step to access private repositories via SSH.
> workflows: yocto-build-deploy: add SSH key to environment

- .github/workflows/yocto-build-deploy.yml
- build/barys
This is required when there is more than one integration layer that provides custom templates like is the case for the secure boot support in meta-balena-hab.
The custom templates in meta-balena-hab add the new layer in `bblayers.conf` hence enabling secure boot support, including the increase in disk space needed.
> Allow to customize sample templates

- .github/workflows/yocto-build-deploy.yml
- automation/include/balena-deploy.inc
- build/barys
- build/generate-conf-notes.sh
Machine refers to the Yocto machine configuration, while slug refers to the balenaCloud device type.
This allows to build the same machine but deploy to a different device type.
> workflows: yocto-build-deploy: distinguish machine from slug

- build/contracts/blueprints/os-contracts.yaml
https://github.com/balena-io/contracts/commit/2903ca430d32ba59fc662ed2a646fcb2aac6e6a0 removed the sw.os-image contract. Removing it from the oscontract blueprint to fix build errors
> generate-oscontracts: remove sw.os-image selector

- build/barys
Keep track of the different machine-image combos being built not to duplicate fields.
This allows to have multiple device types that build the same machine, for example if they have different feature layers.
> barys: build unique machine-image combinations

- .github/workflows/genericx86-64-ext.yml
- .github/workflows/yocto-build-deploy.yml
This allows more granular control over which environments are used for which steps, and avoids requiring a single environment to define how to build, sign, and publish.
Initially this workflow will still fallback to the existing monolith environments and the behaviour should be unchanged.
See: https://balena.fibery.io/Work/Improvement/Update-yocto-scripts-workflow-with-separate-jobs-for-AWS-and-signing-environments-2471
Here are the workflows still pinned to master, generally meaning their builds are broken either way or Renovate would have pinned them to the current yocto-scripts submodule commit.
https://github.com/search?type=code&q=yocto-build-deploy.yml%40master+NOT+repo%3Abalena-os%2Fmeta-balena
> Create jobs to separate AWS environments from build environments

- .github/workflows/yocto-build-deploy.yml
By setting defaults here we are overriding values that may have been set at the device level via deploy-environment.
For now leave them blank until we have rolled out the new environments to all the repositories.
See: https://balena.fibery.io/Work/Project/Separate-balenaOS-signing-environments-from-deploy-environments-1049
See: https://github.com/balena-os/balena-yocto-scripts/pull/481
> Unset the new environment inputs until they have been deployed

- .github/workflows/genericx86-64-ext.yml
- .github/workflows/yocto-build-deploy.yml
Tested with signing environments [here](https://github.com/balena-os/balena-generic/pull/566).
This simplifies the inputs, and keeps them closer to the current device repo workflows. The only change required will be on the 3 secure boot repositories to provide a signing environment ([example](https://github.com/balena-os/balena-generic/pull/566/files)).
> Rename build environment to signing environment

- .github/workflows/yocto-build-deploy.yml
We need most of the files from the root of the artifacts directory for the S3 upload, not just the files in the image directory.
See: https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/Some-finalized-OS-releases-were-missing-S3-files-62
> Unpack all artifacts for S3 upload

- .github/workflows/yocto-build-deploy.yml
This is for use in at least 3 device types - where the customer requires a non-flasher image to be available by default via downloads, but for testing purposes we need ot use the flasher image. This change allows for selecting the flasher image using the test_matrix input - i.e `image: balena-flasher.img`
> Leviathan: Allow specifying alternative image to test

- .github/workflows/yocto-build-deploy.yml
This is needed for private device types to pass the secure boot module signing test.
> workflows: yocto-build-deploy: provide header files to test suite

- build/barys
Commit 8d9f26fb switched to using the wildcard * char inside quotes, which makes ls fail to find the intended directory and thus all builds for older Poky revisions fail. We can fix this by removing the quotes.
> build/barys: Fix builds for older Poky variants

- .github/workflows/yocto-build-deploy.yml
This PR:
- Fixes non-secureboot AMI deploys 
- Disables secureboot AMI publishing - as this no longer works due to incompatibilities with secureboot and preloading: https://balena.fibery.io/Work/Project/Re-implement-secureboot-enabled-AMI's-1460
> AMI deploy: parameterise test org + use testing api key

- .github/workflows/yocto-build-deploy.yml
This grep has started to catch file strings in the cooker logs, even on success, so instead just rely on the success message in the second grep of balena build logs.
See: [#balena-io/os/devices > new imx8mmebcrs16a1 device type @ 💬](https://balena.zulipchat.com/#narrow/channel/360838-balena-io.2Fos.2Fdevices/topic/new.20imx8mmebcrs16a1.20device.20type/near/518678926)
> Remove the old grep for build errors

- .github/workflows/yocto-build-deploy.yml
This will improve the download time for each, and allow
reduction of required hostapp files without breaking tests.
Moving the creation of deflate files to the build job enables us to upload S3 artifacts in both the deploy-S3 and the deploy-hostapp steps (as webresources).
See: https://balena.fibery.io/Work/Improvement/Prepare-deflate-files-before-hostapp-deploy-2913
> Split artifact uploads into hostapp and testing artifacts

- .github/workflows/yocto-build-deploy.yml
- automation/include/balena-deploy.inc
This is the PR that uploads the SBOM (bom.json) and VEX (vex.json) as release artifacts
https://balena.fibery.io/Work/Project/balenaos-SBOM-as-release-asset-1515
Changelog-entry: Generate SBOM and VEX (cycloneDX)
> Add CycloneDX SBOM and VEX generation

- .github/workflows/yocto-build-deploy.yml
We encrypt the manifest if its private/signed, but don't look for the encrypted version to upload - fixes that
> upload hostapp artifacts: include encrypted manifest

- .github/workflows/yocto-build-deploy.yml
The action currently has dependencies on the leviathan base
project so we need to keep them aligned for now.
See: https://balena.fibery.io/Work/Improvement/Update-yocto-scripts-workflow-to-use-leviathan-submodule-2944
> Use the leviathan action from the submodule in meta-balena 
