build/generate-conf-notes.sh

Sample fixed output:
```
Resin specific targets are:
resin-image
Hummingboard (EXPERIMENTAL)         : $ MACHINE=cubox-i bitbake resin-image
Nitrogen 6X (EXPERIMENTAL)          : $ MACHINE=nitrogen6x bitbake resin-image
```
[Issue #5]
@petrosagg @floion @telphan
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-yocto-scripts/6)

generate-conf-notes.sh: Fix conf-notes.txt content

---

build/build-device-type-json.sh

before recreating the new ones.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-yocto-scripts/7)

build-device-type-json.sh: Remove old .json files

---

build/barys

---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-yocto-scripts/10)

barys: activate RESINHUP in production builds

---

automation/jenkins_build.sh

jenkins_build.sh: Remove build at the end

---

automation/jenkins_build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-yocto-scripts/11)

Add support for compressed artifacts.

---

README.md
build/barys

barys: Update HARD ASSUMPTIONS section

---

automation/Dockerfile
automation/jenkins_build.sh
automation/prepare-and-start.sh

@floion @telphan @Page- @petrosagg

Support for yocto builds in docker

---

automation/jenkins_build.sh
build/barys
build/barys.changelog

@telphan @floion @petrosagg @Page- 
Connects to resin-os/meta-resin#137

Don't force supervisor tag

---

build/barys
build/barys.changelog

@floion @telphan @petrosagg 
Connects to resin-os/meta-resin#128

barys: Replace RESIN_STAGING_BUILD by DEBUG_IMAGE

---

automation/jenkins_build.sh

jenkins_build.sh: --staging was replaced by --debug-image

---

automation/jenkins_build.sh

Add a env ENABLE_TESTS - that allows for disabling of tests or overriding in specific cases.

---

build/barys

barys: Clarify invalid argument reason

---

automation/jenkins_build.sh
build/barys

@agherzan @floion 
Connects to resin-os/meta-resin#315

Replace DEBUG_IMAGE with DEVELOPMENT_IMAGE

---

automation/jenkins_build.sh

connect https://github.com/resin-os/resinos/issues/155

jenkins_build.sh: Upload production resinhup packages to registry.resinstaging.io

---

automation/jenkins_build.sh

This reverts commit de6ca4d930af5ad0a2aa11be6b0f5320369241dc.

Revert "jenkins_build.sh: Run resinio builds with this script"

---

automation/Dockerfile_yocto-build-env
automation/prepare-and-start.sh

Connected to https://github.com/resin-os/resinos/issues/181

Use /var/lib/docker as VOLUME

---

automation/Dockerfile_yocto-build-env
automation/prepare-and-start.sh

Connected to https://github.com/resin-os/resinos/issues/181

[1.X] Use /var/lib/docker as VOLUME

---

build/barys
build/barys.changelog

Connects to https://github.com/resin-os/resinos/issues/126

Rename RESIN_SDIMG_COMPRESSION to RESIN_RAW_IMG_COMPRESSION to follow resinOS

---

automation/jenkins_build.sh

jenkins_build.sh: Deploy to s3 and support build flavors

---

automation/jenkins_build.sh

jenkins_build.sh: Expect resinhup only in managed/nondev

---

automation/jenkins_build.sh

jenkins_build.sh: Set latest in the container

---

automation/jenkins_build.sh

jenkins_build.sh: prepare.coffee depends on latest file

---

automation/jenkins_build.sh

jenkins_build.sh: Push resinhup images only for managed ones

---

automation/jenkins_build.sh

jenkins_build.sh: Use zip from compressing images

---

automation/jenkins_build.sh

Upload an empty IGNORE file before uploading image files, remove it once the upload is finished.
This will allow the image maker to ignore incomplete versions.
[related image maker PR](https://github.com/resin-io/resin-image-maker/pull/73)

IGNORE file in build folder while files are being uploaded

---

automation/jenkins_build.sh

These don't seem to be used anywhere.

automation/jenkins_build.sh: Remove unused variables

---

build/generate-conf-notes.sh

jq can take the path as it's last argument.

pass the json file as argument to jq

---

automation/jenkins_build.sh

jenkins_build.sh: Also deploy non-flasher images

---

build/barys

Fixes https://github.com/resin-os/resinos/issues/350

barys: Add more information for dry run flag

---

build/barys

Set the supervisor tag value in local.conf after settig the
default value in order to avoid the value being overwritten.

build/barys: Set supervisor tag last

---

automation/jenkins_build.sh

jenkins_build.sh should also be able to run outside of the jenkins environment
and run the yocto build in a docker container.

jenkins_build.sh: Allow non-jenkins docker container builds (on 1.X)

---

automation/jenkins_build.sh

Signed-off-by: Petros Angelatos <petrosagg@gmail.com>

Support uploading resinhup archives using the new hostapp output

---

automation/jenkins_build.sh

Signed-off-by: Theodor Gherzan <theodor@resin.io>

Pull the latest resin-img before we run the deploy

---

automation/jenkins_build.sh

Signed-off-by: Theodor Gherzan <theodor@resin.io>

When pulling resin-img use tag master

---

automation/jenkins_build.sh

jenkins_build.sh: Fix typo when using the deployTo variable

---

build/package.json

[Issue resin-os/resinos#403]
Improve commoninstructions for installing resinOS on a device

package.json: Update device-types package to latest version

---

build/barys

barys: Set SUPERVISOR_TAG when using a custom supervisor tag

---

automation/jenkins_build.sh

Make 'latest' text file publicly accessible on S3

---

automation/jenkins_build.sh

jenkins_build.sh: Add support for device types that don't deploy raw images

---

build/barys

barys: Add support for custom bitbake target

---

automation/prepare-and-start.sh
build/package.json

Switch from resin-yocto-scripts to balena-yocto-scripts

---

build/barys

Now that meta-resin is renamed to meta-balena we do
the same change here.
Changelog-entry: Parse by meta-balena- instead of by meta-resin-

barys: Parse by meta-balena-

---

automation/jenkins_build.sh

This file will be uploaded both as a jenkins artefact and to s3

Store rootfs manifest

---

automation/jenkins_build.sh

Push and tag dev images to dockerhub

---

automation/jenkins_build.sh

jenkins_build.sh: Use correct bash variable assignment

---

automation/jenkins_build.sh

jenkins_build.sh: Rename device type icon to logo.svg

---

automation/jenkins_build.sh

jenkins_build.sh: Use new s4cmd params for accessing s3

---

automation/prepare-and-start.sh

Support building older resin OS releases

---

automation/jenkins_build.sh
automation/start-docker-and-push.sh

Tag ESR releases with meta balena base version

---

automation/start-docker-and-push.sh

Update balenaos account to balena_os

---

automation/jenkins_build.sh

jenkins_build.sh: Fix passing additional argument to barys

---

automation/jenkins_build.sh

Stop pushing images in the resinos folder

---

automation/jenkins_build.sh

Set S3 access policy to private for private DT
and don't deploy private DT to dockerhub
This is untested (and I don't know how this script gets tested),
but I believe these are the only changes necessary to support private DTs.
Let's sync in chat on testing this, I just wanted to get the ball rolling.
Signed-off-by: Stevche Radevski <stevche@balena.io>

Manage deploying private device types

---

automation/jenkins_build.sh

Fix s3 bucket reference

---

automation/Dockerfile_balena-push-env

Update balena-cli version to 11.35.4

---

README.md

Signed-off-by: Alexandru Costache <alexandru@balena.io>

README: Rename 'resin' occurrences in documentation

---

automation/jenkins_build.sh

Signed-off-by: Stevche Radevski <stevche@balena.io>

Check DT privacy against the API

---

esr/esr_release.py

esr: Add branch creation automation script

---

automation/Dockerfile_balena-push-env
automation/balena-push-os-version.sh
automation/jenkins_build-containers.sh
automation/jenkins_build.sh
automation/prepare-and-start.sh
build/barys

* Parametrize application, target image and docker registry names to allow for easier development
* Authenticate with balena registry
* Allow barys to build multiple bitbake targets

Parametrize repository names and other generic changes

---

automation/jenkins_build.sh

tests: strip leading paths when packaging

---

automation/jenkins_build.sh

tests: fix typo in tests packaging

---

automation/balena-docker.inc

This is a leftover from development.

balena-docker: Remove execution trace flag

---

automation/balena-lib.inc

Match the file style and use tabs to indent. Only cosmetic changes.

balena-lib: Fix indentation to tabs

---

automation/balena-api.inc
automation/balena-deploy.inc
automation/balena-lib.inc
automation/jenkins_build.sh

Specifically there are now library functions to:
* Deploy Jenkins artifacts
* Deploy to dockerhub/S3

Extract functionality from jenkins_build to script libraries

---

automation/balena-build.sh
automation/balena-deploy-block.sh
automation/balena-deploy.inc
automation/balena-lib.inc

* Fix some shellcheck warnings
* Pass environment to balena_lib_token
* Adjust balena_deploy_block environment variables to use both for hostapp and blocks and also standalone calling.

MIscellaneous improvements

---

automation/include/balena-lib.inc
automation/jenkins_build-containers.sh
build/balena-build.sh

Fix the balena-build script to correctly pass the development mode flag, and a couple of improvements.
Tested on a raspberrypi4-64 development test build.

Miscellaneous fixes

---

automation/include/balena-deploy.inc

Connects-to: https://github.com/balena-os/meta-balena/pull/2174

Substitute device type in config.js if present

---

automation/entry_scripts/balena-deploy-block.sh
automation/include/balena-api.inc
automation/include/balena-deploy.inc
automation/include/balena-lib.inc

This will be used by the jenkins build jobs when deploying to staging and production.

Create public app when deploying a hostapp

---

automation/Dockerfile_yocto-build-env
automation/include/balena-docker.inc

These will solve the container networking problems with the default bridge network in the build.

Set docker version to match build system and do not force dockerd settings

---

automation/include/balena-deploy.inc

tests: Substitute deviceType with MACHINE when packaging tests

---

automation/include/balena-docker.inc
automation/include/balena-lib.inc
automation/include/semver2.sh

Extend script libraries to support hostOS blocks building.

Add missing library functions to successfully build hostOS blocks 

---

automation/include/balena-api.inc
automation/include/balena-deploy.inc
automation/include/balena-docker.inc
automation/include/balena-lib.inc
automation/jenkins_build-blocks.sh
automation/jenkins_build.sh
build/balena-build.sh

* Add a conditional verbosity mode
* Fix installation directory for block deployment scripts
* Modify block contracts to specify separately recipes and packages
* Fix setting app roles on non-production environments

Miscellaneous fixes/improvements

---

automation/Dockerfile_balena-push-env
automation/entry_scripts/balena-deploy-block.sh

Some functions in balena-api require this library.

balena-deploy-block: source balena-lib script library

---

automation/include/balena-deploy.inc

Use slug when setting deviceType for leviathan

---

automation/include/balena-deploy.inc

Substitute the worker types for generic device slugs

---

automation/entry_scripts/balena-deploy-block.sh
automation/include/balena-api.inc
automation/include/balena-deploy.inc
automation/include/balena-lib.inc
automation/jenkins_build-blocks.sh

ESR hostapps need the following labels:
* release-policy: esr
* esr-current
* esr-next
* esr-sunset
This set labels them appropriately.

Automate labelling of ESR hostapps

---

automation/entry_scripts/prepare-and-start.sh

The login will happen as needed.

prepare-and-start: Remove balena login

---

build/barys

This has now been removed from meta-balena.

barys: Remove RESINHUP setting

---

automation/include/balena-deploy.inc

balena-deploy: s/resin-flasher/balena-flasher

---

automation/jenkins_generate_ami.sh

Pass environment to docker

---

automation/entry_scripts/balena-generate-ami.sh

See, https://www.flowdock.com/app/rulemotion/i-cli/threads/CXfkrm2cZNag4S_qlEY-NPHZkfq
* the CLI prompts for input during preload
Alternatively, the --pin-device-to-release flag may be used to pin only the
preloaded device to the selected release.
Would you like to disable automatic updates for this fleet now? No
* we do not want to set the suggested flag and we do not want to touch the fleet release policy for this use case

Unattended preload operation

---

automation/entry_scripts/balena-generate-ami.sh

Remove superfluous preload flag

---

automation/include/balena-deploy.inc

This PR works in coordination with https://github.com/balena-io/balena-img/pull/340

deploy: push image variant artifacts

---

automation/Dockerfile_balena-push-env
automation/Dockerfile_yocto-build-env
automation/entry_scripts/balena-deploy-block.sh
automation/include/balena-api.inc
automation/include/balena-deploy.inc
automation/include/balena-lib.inc
automation/jenkins_build.sh

Separate the release deploy and finalise steps.

Build and deploy

---

.github/workflows/flowzone.yml

workflows: add flowzone

---

automation/Dockerfile_yocto-build-env

Dockerfile: yocto-build-env: update balenaCLI to 14.5.15

---

automation/jenkins_build.sh

jenkins_build: accept bitbake extra arguments

---

automation/entry_scripts/balena-generate-ami.sh
automation/jenkins_generate_ami.sh

* Add the secureboot feature to OS contracts
* For signed images, opt in secure boot in the AMI images

Secure boot support

---

.github/workflows/flowzone.yml

flowzone: allow external contributions

---

automation/Dockerfile_balena-push-env
automation/Dockerfile_yocto-build-env
automation/entry_scripts/balena-deploy-block.sh
automation/include/balena-api.inc
automation/include/balena-deploy.inc

balena-api: add release assets helper functions

---

automation/include/balena-deploy.inc

As per internal thread https://balena.zulipchat.com/#narrow/stream/345890-balena-io/topic/Jenkins.20build.20failures/near/409602914

automation/balena-deploy: Pin to known working version of balena-img

---

automation/entry_scripts/balena-generate-ami.sh
automation/include/balena-deploy.inc

Enable S3 Server Side Encryption flags

---

.github/workflows/yocto-build-deploy.yml

Reduce the required secrets and inputs required by relying on vars and secrets set in each GitHub Environment.

Refactor secrets and variables to use environments

---

.github/workflows/yocto-build-deploy.yml

Fix actionlint errors and warnings in shell steps

---

automation/include/balena-deploy.inc

balena-deploy: deploy secure boot lock artifacts if available

---

.github/workflows/yocto-build-deploy.yml

only login to s3 if deploying to s3

---

.github/workflows/yocto-build-deploy.yml

Use App Installation tokens so we can clone private submodules

---

.github/workflows/generic-amd64.yml
.github/workflows/yocto-build-deploy.yml

Based on suggestions here: https://github.com/balena-os/balena-yocto-scripts/pull/379

Rework inputs 

---

.github/workflows/yocto-build-deploy.yml

checkout private contracts for test job

---

.github/workflows/yocto-build-deploy.yml

This makes it more human readable, and allows us to treat patch, minor, and major revisions of the action differently if needed.

Include semver when bumping leviathan action

---

.github/workflows/yocto-build-deploy.yml

Add pull request write permissions for workflow approvals

---

.github/workflows/yocto-build-deploy.yml

This functionality never worked for various reasons - and shouldn't be in this workflow anyway
Currently replaced with manual creation, documented internally

Remove hostapp creation step

---

.github/workflows/yocto-build-deploy.yml

Unset AWS credentials to avoid overriding MinIO credentials

---

.github/workflows/yocto-build-deploy.yml

Upload yocto build logs with existing artifacts

---

.github/workflows/yocto-build-deploy.yml

See: https://balena.fibery.io/Work/Improvement/Cancel-the-Jenkins-NFS-host-via-Hetner-2474

Remove legacy yocto NFS cache host setup

---

.github/workflows/yocto-build-deploy.yml

workflows: yocto-build-deploy: pass device type to build

---

.github/workflows/yocto-build-deploy.yml

Fix check for present test matrix when checking test results
